apiVersion: apps/v1
kind: Deployment
metadata:
  name: convtemp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: convtemp-app
  template:
    metadata:
      labels:
        app: convtemp-app
    spec:
      containers:
      - name: convtemp
        image: felipefranca93/convtemp:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: convtemp-app
spec:
  selector:
    app: convtemp-app
  ports:
    - protocol: TCP
      port: 8080
  type: NodePort
  


