
name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s_CONFIG }}
